service: AUTHENTICATION-SERVERLESS-SDP15
frameworkVersion: "3"

custom:
  tableName: "users-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role: arn:aws:iam::972684985783:role/LabRole
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
